### PR TITLE
updated extract particle protocol

### PR DESCRIPTION
**Pull request by josuegbl**

### CODE REVIEW

**Comment by pconesa** [comment]
Something is not working @josegutab. Extract particle in TesXmippWorkflow dos not fail, but it does not generate any set of particles:
image

**Comment by delarosatrevin** [comment]
Maybe we can add to the test a simple check that the output is not None.

**Comment by pconesa** [comment]
Well, it fails right after when the next protocol try to use the output. 
I mean the test actually fails but in the next "box"

**Comment by pconesa** [comment]
related to #905

**Comment by pconesa** [comment]
should fix #903

**Pull request merged**
