### PR TITLE
Release 1.2.1 to devel

### PR DESCRIPTION
**Pull request by pconesa**

### CODE REVIEW

**Comment by pconesa** [comment]
@delarosatrevin , @josuegbl could you please double check this make sense. This are release-1.2.1 changes, with "sdevel" changes included, going to devel.

**Comment by delarosatrevin** [comment]
@pconesa I think that @josuegbl already merged the changes in the other PR (so, I hope that he checked the changes). I'm not on top of the changes in devel, so maybe other person should double-check that everything work as expected before merging.

**Comment by pconesa** [comment]
Well, committee here should be only those in release-1.2.1. they look to me.

The thing, is that comparing this branch with @josuegbl...appears more changes that expected.

**Comment by pconesa** [comment]
I've done this wrong. I'm cancelling.

**Pull request closed without merging**
