### PR TITLE
Hotfix picking in tmp folder warning + saving in protected folder or file.

### LINKED ISSUE #331: Warn if the user picks in the Tmp folder of the written coordinates
This issue is related to #330 , before we used a misleading question to load an existing tmp directory (which, by the way, did not took into account the time of modification of the set of coordinates).

I more clear solution could be warn the user when picking in a tmp directory and leaving without saving changes.

### LINKED ISSUE #452: Showj: Crash when saving into a directory without write permissions
It should show an error in this case, but not crash.

### LINKED ISSUE #463: Xmipp picking: warn user of unsaved changes when pressing the "Close" button.
Now only if you close the picking using the window controls, the user is warned about loosing changes. 

Add the same behavior when pressing the button Close.

### PR DESCRIPTION
**Pull request by pconesa**
Also, consistent behavior between closing the window and pressing the close button in the picker.
Closes #463 
Closes #331 
Closes #452

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@josuegbl , change to the PR branch, compile it, and check if the expected behavior was the one we dicussed. If everything is fine, merge into v1.0.

**Comment by pconesa** [comment]
Wait @josuegbl ....the Java code is fine, but forgot to modify the call from python. Do not merge yet, please.

**Comment by pconesa** [comment]
@josuegbl Ready!

**Comment by josuegbl** [comment]
waiting for more changes @pconesa

**Comment by pconesa** [comment]
Sorry @josuegbl , don't need these changes in the other branch. So this pull request is ready, and soon I'l create another, once I finish.

**Comment by pconesa** [comment]
Merged with branch that fixes #452

**Comment by delarosatrevin** [comment]
@pconesa , @josuegbl It is ready to merge? I'm going to update some Scipion installation over here and would be good to have this fix.

**Comment by pconesa** [comment]
@josuegbl , @delarosatrevin ready from my side.

**Pull request merged**
