### PR TITLE
Added a new package (cryomethods) and also it first protocol.

### PR DESCRIPTION
**Pull request by josuegbl**
This PR contain the first protocol of cryomethods packages. It should be merge after @delarosatrevin 's merge.

### CODE REVIEW

**Comment by pconesa** [comment]
@josuegbl , I might not be able to update your branch? sdevel is merged but still can see commits here from that PR.

**Comment by delarosatrevin** [comment]
I already updated @pconesa.

**Comment by delarosatrevin** [comment]
Did you tested it, @pconesa ? I don't trust @josuegbl, even if he created a test for it! ;)

**Comment by pconesa** [comment]
no, but y don't want him to rant about this PR waiting ;-),...and I'm also adopting future behaviour. This is, except for one line, only a plugin thing. In the future, this will be the responsibility of the plugin "manager"...thus....Josue!.

**Pull request merged**
