### PR TITLE
Fix parse gctf

### PR DESCRIPTION
**Pull request by delarosatrevin**
@azazellochg I has fixed a bug in parsing Gctf log files.
When the 'High resolution refinement' and not the 'Phase shift estimation' the line produced was as below:

23846.26    23525.42       61.84    0.521613  Final Values (Hres refine)

Adding the extra '(Hres refine)' string and making the number of elements after split greater...and broken the current parsing. 

I have changed the parsing a little bit and this error is fixed. Can you double check my changes to make sure it is working as expected? (I have passed the Gctf tests already)

### CODE REVIEW

**Comment by azazellochg** [comment]
@delarosatrevin I'll check it as soon as I can ;)

**Comment by delarosatrevin** [comment]
Ok, great! Thanks for your help.

**Comment by azazellochg** [comment]
@delarosatrevin it looks ok. The only thing I noticed is that defocus values are swaped and defAngle=defAngle(GCTF)+90. Was this always like this and I didn't pay attention?

**Comment by delarosatrevin** [comment]
@azazellochg I only changed the way the values were parsed. The CTF defocus values are "standardized" according to the EMX definition. You can see the function here:
https://github.com/I2PC/scipion/blob/master/pyworkflow/em/data.py#L191

If it is working fine, we can merge and delete the branch.

**Comment by azazellochg** [comment]
ah yes, forgot about this standardize function. Good to go!

**Pull request merged**
