### PR TITLE
Rm resolution v3

### PR DESCRIPTION
**Pull request by rmarabini**
fix some bugs introduced after adding resolution and fitQuality to ctfModel.

Tests: 
././scipion test --grep ctf --run
./scipion test tests.em.data.test_convert_xmipp

### CODE REVIEW

**Comment by pconesa** [comment]
@rmarabini, there are a couple of conflicts here (should be easy for you to resolve them) Once done, @josuegbl , could you proceed to review and accept if all is ok?

**Comment by rmarabini** [comment]
hi @josuegbl  and @pconesa,ç

  Conflicts solved ;-).

**Comment by pconesa** [comment]
Great! @rmarabini , many thanks.

**Comment by delarosatrevin** [comment]
@rmarabini, The CTF streaming test is still failing in this branch:

scipion test --grep ctf treaming --skip test_programs_xmipp --run

I updated the latest changes from release-1.1.facilities-devel, but I went to the commit before these changes and in both cases that test fails.

**Comment by pconesa** [comment]
I'm testing this and can confirm the same issue here. It seems that XmippCtfEstimation does not store the resolution:

image

**Pull request merged**
