### PR TITLE
Fix error when deleting a project in manager.py

### LINKED ISSUE #1700: Error project window
I have detected a bug when we create a new project and we delete it. After delete the project an error appears when we try to open another project created.
screenshot from 2018-07-23 12-51-17

### PR DESCRIPTION
**Pull request by pconesa**
On behalf of @fonsecareyna82.

Closes #1700

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Thanks @fonsecareyna82 and @pconesa for dealing with this issue. 

The main problem here was that Project.create function change the current working directory to the new project path. This break the deletion after from the Projects GUI. 

Instead of the proposed solution (changing the cwd to the PROJECTS dir, that might no be the original directory), I made a commit with the following change: 
* store cwd
* create project
* restore cwd

I think this is more clean since does not assume any location and just restore the cwd.

**Comment by pconesa** [comment]
@delarosatrevin , @fonsecareyna82 this is causing tests to fail. @ldelcano is doing some test now but seems to break the tests.

We can undo this or review what the test are doing?

**Comment by delarosatrevin** [comment]
Yes, maybe these change is affecting tests (some or all?) that were assuming this side effect of moving to the project folder. I will propose to keep the change and review the failing cases. I would prefer to keep the new behaviour of not changing the current location when creating a project.

**Comment by ldelcano** [comment]
Yes, José Miguel, it is affecting all tests. I do not know if also when creating workflows from a json.

**Pull request merged**
