### PR TITLE
fix relion movie #1227

### LINKED ISSUE #1227: relion movie refinement fails
Reported by Dmitry Semchonok:
1.1-facilities-devel branch. Movie refinement seems to use wrong inputs (original extracted particles, not the output) and hence, fails at the first metadata conversion step
image_from_skype

### PR DESCRIPTION
**Pull request by azazellochg**
closes #1227 
I checked it in relion 1.4 and 2.1

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Hi @azazellochg Is there any test that I could run related to this change?

**Comment by azazellochg** [comment]
Hi @delarosatrevin, you can check it the following way:
1) extract particles
2) run auto-refine with ALL extracted particles
3) extract movie particles
4) run movie refinement (continue mode, auto-refine with movies)
The last protocol will fail at mdAux.copyColumn(md.RLN_ORIENT_ORIGIN_X_PRIOR, md.RLN_ORIENT_ORIGIN_X), because mdParts will have no alignment data.

**Comment by delarosatrevin** [comment]
Thanks @azazellochg , @josuegbl since you have this protocol more fresh, could you check this PR?

**Comment by josuegbl** [comment]
Ok @delarosatrevin, ill review the PR.

**Comment by delarosatrevin** [comment]
@josuegbl Have you had the chance to check this PR? I would be good to clean up as many PR as we can.

**Comment by josuegbl** [comment]
@delarosatrevin Im checking this PR.

**Pull request merged**
