### PR TITLE
CTF phase shift

### LINKED ISSUE #1208: phase shift not written by 'relion - export ctf'
Protocol 'relion - export ctf' does not write the value of phase shift in the output STAR file.

### LINKED ISSUE #1370: rlnPhaseShift is not propagated in relion
The similar thing that we had with groupName, phase shift determined by ctf programs is not propagated neither when doing particle extraction, nor when doing convertInputStep in any relion protocol

### PR DESCRIPTION
**Pull request by azazellochg**
@pconesa is is still possible to add this into release? If not, please tell me where should I merge this (this branch is created from from release-1.1-facilities-fixes).

This PR:
- [x] adds ctfPhaseShift to CTF model
- [x] fixes relion ctf export protocol (closes #1208 )
- [x] fixes phase shift conversion from ctffind (output is in radians, we need degrees)
- [x] fix specific CTF viewers (they are not displayed for new projects with _resolution and _fitQuality params): see [here](https://github.com/I2PC/scipion/blob/release-1.1.facilities-devel/pyworkflow/em/viewer.py#L245)
- [x] show freq both in freq and Angstroms in all ctf wizards (f900f82)
- [x] enable slow exhaustive search in ctffind 4.1.5 and 4.1.8 (4447572), since 

> slower search (a la 4.0) is now default, because of reports the faster 1D search was significantly less accurate (thanks Rado Danev & Tim Grant)

- [x] close #1370 

This PR will definitely need some testing as we did when adding maxResolution and fitQuality.

### CODE REVIEW

**Comment by azazellochg** [comment]
sorry, wrong base nranch

**Comment by pconesa** [comment]
@azazellochg , this is delicate, although it could go into the release, but need to be reviewed by someone else apart from myself. Let me merge fixes first to see if this review will be clean form fixes changes.

**Comment by delarosatrevin** [comment]
@pconesa I can take a look a this changes and fix the CTF viewer that @azazellochg pointed out. If everything is fine, can I merge it into facilities-devel?

**Comment by pconesa** [comment]
Yep; I trust you. Obviously!

**Comment by delarosatrevin** [comment]
@azazellochg, @pconesa This PR seems fine to me...I did some small fixes and related tests to CTF are passing. So, I think it is fine for me, it can be merged.

**Comment by azazellochg** [comment]
Looks good to me, thanks @delarosatrevin !

**Pull request merged**
