### PR TITLE
add eman2.21a to devel

### LINKED ISSUE #766: eman2 mpi support
Are there currently any plans to implement mpi support for eman2?

### LINKED ISSUE #1500: import particles from EMAN2
somehow this is missing in the list of options...

### PR DESCRIPTION
**Pull request by azazellochg**
This is a large PR, which comprises new Eman2 version support and a few things related to RCT protocols. I would like to request as many reviewers as possible since there are lots of changes. I am sorry that there is only one commit, but cherry picking from 1.2-based branch was not successfull due to too many differences between 1.2 and devel..

Global changes:
1) Eman2 updated to v2.21a, added EMAN2SCRATCHDIR var and mpi support to protocols
2) constants.py file added combining all params from Eman protocols
3) added readCTFModel func to read CTF from json files (xmipp cannot read hdf header yet)
4) EMANMPIOPTS env var can be used by Scipion as SCIPION_MPI_FLAGS
5) code formatting for all eman protocols, all of them are updated to support new EMAN2.21 options
6) new test data for eman2 added (mostly for tilt validation test)

Bugfixes etc:
1) writeSetOfParticles fixes: output files are named according to micName or micId
2) e2converter write: propagate pix size, fixed wrong angle conversion for 2D/3D
3) XmippProtExtractParticlesPairs has ctf options added
4) added option to Eman refine easy to display html report
5) This PR closes #766 and #1500

New protocols:
1) ProtImportCoordinatesPairs to import tilt coord pairs from xmipp3 or eman2 (+test)
2) Import ctf protocol now supports eman *json files
3) EmanProtCTFAuto for e2ctf_auto.py in particles (with test and viewer)
4) EmanProtRefine2D, EmanProtRefine2DBispec for 2D classification (with tests)
5) EmanProtTiltValidate for e2tiltvalidate.py (with test and viewer)
6) EmanProtAutopick for new fully automatic e2boxer.py
7) EmanProtBoxing updated to run both old and new e2boxer.py in interactive mode

New tests:
1. scipion test em.packages.eman2.tests.test_protocols_eman.TestEmanTiltValidate
2. scipion test em.packages.eman2.tests.test_protocols_eman.TestEmanRefine2DBispec
3. scipion test em.packages.eman2.tests.test_protocols_eman.TestEmanRefine2D
4. scipion test em.packages.eman2.tests.test_protocols_eman.TestEmanCtfAuto
5. scipion test tests.em.protocols.test_protocols_import_coords.TestImportCoordinatesPairs

New test data (unpack into data/tests/eman) - might be partially on the server already:
[50Mb](https://mega.nz/#!F4wjXJBT!k9FMtTiemc3vh8ltRd1TmIp-NV9s7QzgNVxCDDa8Tro)

New eman2 tgz to upload to server: [440Mb](https://mega.nz/#!wspyCTSR!-8M5B9hU9dcfufd2_Lbal31YHJ20cKcc_UF4zGn2pRg)

Remaining todo list:
- [x] fix new eman installation
- [x] import particle set (lst) from Eman (close #1500)
- [x] test for EmanProtAutopick
- [x] add option to skip e2ctf.py step in convertInputStep (if particle set comes from eman already and they are phase flipped)
- [x] add option to input bispectra for refine2d protocol, that should match input particles (so the y are not generated from scratch again)
- [x] add iterations into refine2d viewer
- [x] add continue option to refine2d (however, not avail for bispec!)

PS. I tested it as much as possible with eman-2.12 and 2.21a, but that was only me :)
Pablo, Josue, and Jose, you all have write permissions to push to my branch in this PR.

### CODE REVIEW

**Comment by pconesa** [comment]
Thanks @azazellochg ....so far I'm impress with the volume of changes....I'll review it. I'm guessing that same protocol is used for different eman installations?

**Comment by azazellochg** [comment]
@pconesa there are few new protocols which are only available for 2.21 and there are some which are updated to support both old/new version. This is what you were asking?

**Comment by delarosatrevin** [comment]
Excelent @azazellochg ! I would be happy to join the reviewers group of this PR. 
@pconesa, Despite the number of changes, most of them are eman-related. 

Another thing, would be this PR better merged after a preliminary pluginization version?

**Comment by azazellochg** [comment]
Some ideas for improving:
- [ ] add option to skip e2ctf.py step in convertInputStep (if particle set comes from eman already)
- [ ] add option to input bispectra for refine2d protocol, that should match input particles (so the y are not generated from scratch again)
- [ ] ...

**Comment by pconesa** [comment]
I must apologize for not putting the files on the server, sorry @azazellochg and the rest. Now they are ready.

**Comment by azazellochg** [comment]
@pconesa I thought this is the current way to handle tests that are not supported by old software versions: raise an exception. The same way some new relion protocols will fail if running relion 1.4. I guess after pluginization the tests that are not supported by the software version should be hidden.

**Comment by azazellochg** [comment]
Closing this, the eman-related changes are now in https://github.com/scipion-em/scipion-em-eman2. I will later create a new PR with xmipp-only changes.

**Pull request closed without merging**
