### PR TITLE
Fixed several spider bugs

### PR DESCRIPTION
**Pull request by delarosatrevin**

### CODE REVIEW

**Comment by josuegbl** [comment]
Selection of classes2D, from classify ward protocol, fails.

**Comment by azazellochg** [comment]
I would suggest to backport spider-related fixes from devel to this branch (into 1.0.1 eventually), since we fixed there alignment parameters transfer and stack writing.

**Comment by delarosatrevin** [comment]
@azazellochg , Totally agree, we should back-port those fixes. We need to be careful since there is a modification in the ImageHandler class, we need to be sure not to break something else.

**Comment by azazellochg** [comment]
@delarosatrevin , I have done it however you might want to re-check the last changes after me.  Also, commit cd443bc closes #56

**Comment by delarosatrevin** [comment]
Thanks a lot @azazellochg ! I have looked carefully and the back-port seems correct.
I also passed some basic tests and others related to Spider (all finished correctly).

I will keep this PR opens until and can fix the remaining issues.

**Comment by azazellochg** [comment]
In _Spider align ap sr_ protocol we should remove centering option - it is not used. Centering is done using a low-pass filtered disc. Or, we could modify original Spider apsr4class.msa script.

**Comment by delarosatrevin** [comment]
Last commits fix all issues mentioned in #411.
@azazellochg , could you double-check and approve the merge?

**Comment by delarosatrevin** [comment]
I'm adding a last change, to remove classes with only one child in the display tree.

**Comment by azazellochg** [comment]
@delarosatrevin , great work here! all issue look fixed to me. What do you think about centering option in ap sr?

**Comment by delarosatrevin** [comment]
If the centering option is not used, I think the best option right now is to remove it from the protocol (I can do that)...since @taputechnic have updated some of the scripts, maybe we should plan an update for the 1.1 release.

**Pull request merged**
