### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by pconesa**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Merging directly into master?

**Comment by pconesa** [comment]
Weird, right? this is are some github files (templates for issues: Bug or feature).

**Comment by delarosatrevin** [comment]
Can't be merged with the upcoming release?

**Comment by pconesa** [comment]
Nope! I actually did all through github settings page and ended up doing a PR to master.

**Comment by pconesa** [comment]
Well, since it's a branch I guess yes...but may need to do a git merge release-1.2.1....I don't think is worth it...later this will be merged

**Pull request merged**
