### PR TITLE
replace wget cmd with curl

### PR DESCRIPTION
**Pull request by yaizar**
Change the download command to avoid the zero size files when the download fails

### CODE REVIEW

**Comment by pconesa** [comment]
I've been testing this, the idea was to be more robust to downloads errors. Turns out that what we already had is also robust..I need to do more test but this might not improve anything? Or I'm missing the scenario where this would improve it.

**Comment by azazellochg** [comment]
I had few times when the file didn't exist on server ending up with a few kB tgz file (with 404 header I guess) and then it tried to continue the installation..

**Comment by pconesa** [comment]
I've tried that but never manage to end up with "bytes" in the file.....In that case, I think even curl will fail...unless, this cannot happen with curl.

**Comment by delarosatrevin** [comment]
If there is no clear advantage, I will keep it as it is. Indeed, we are downloading to a temp file and then moving. Maybe we could concatenate both commands (wget .. || mv ..) so in case of error the temporary wrong-size file does not end as the expected file.

**Comment by pconesa** [comment]
I'm leaving this out.

**Pull request closed without merging**
