### PR TITLE
add Mltomo to devel

### PR DESCRIPTION
**Pull request by azazellochg**
Since relion still cannot classify tomograms/rcts without an input reference, we still use mltomo xmipp2.4 in the lab. I still have to test whether mltomo works in xmipp3 at all (i have reported problems in 2014, looks like nothing changed..) :)

Anyway, here is the first version of this protocol for scipion. It is not strictly necessary to include it into 1.1.0, could be merged later. I had to modify the xmipp code as well since the output format was not compatible with modern xmipp (no classes/classXXXXXX tables in output metadata, also buggy file names).

In this PR:
1) the protocol
2) simple viewer and
3) test protocol

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Hi @azazellochg...are you still willing to integrate mltomo protocol? I'm not sure if it is working in Xmipp 3 and it is very unlikely that it will be supported. :(

**Comment by azazellochg** [comment]
Hi @delarosatrevin oh, I didn't know this ptrogram was abandoned... I remember comparing source code between 2.4 and 3 and only saw format/metadata changes, but not the program code. It did work in 2.4 and we used to use it a lot, I'll try to check this. If this is not supported, I guess I will keep a branch in my repo for myself :)

**Comment by delarosatrevin** [comment]
Yes, in theory it should only be changes regarding format and
metadata...and we could even consider to have the protocol if it is useful
for you...but in general the ML programs in Xmipp are not active maintained.

**Comment by azazellochg** [comment]
@delarosatrevin Alright, on a small test data it seems to work (splitting 20S proteasome from thermosome), both CC and ML methods. I will test on real tomos soon and then will ask to review the PR.

**Comment by delarosatrevin** [comment]
Great job @azazellochg!!! Thank you so much. Let me know when ready and I will take a look at the PR.

**Comment by azazellochg** [comment]
@delarosatrevin I think it's ready now. I have attached the test data in the folder `ml_tomo` that you should put into `data/tests/xmipp_programs/input/` folder. 
[ml_tomo.tar.gz](https://github.com/I2PC/scipion/files/1385033/ml_tomo.tar.gz)

**Comment by delarosatrevin** [comment]
Hi @azazellochg, are you ready with the changes in this PR? I will try to review it and merge the changes into devel. But I can not do it before the beginning of Nov (not that far away).

**Comment by delarosatrevin** [comment]
Ok, I was writing and then you message came.

**Comment by azazellochg** [comment]
@delarosatrevin any chance you had a look at this ? :)

**Comment by delarosatrevin** [comment]
Hi @azazellochg, I just returned to Europe from my vacations (with not much access to internet). I promise that I will review this PR as soon as possible. My apologizes for the delay.

**Pull request merged**
