### PR TITLE
Release 1.1.facilities stream picking

### PR DESCRIPTION
**Pull request by josuegbl**
- All automatic pickings support streaming mode.
- xmipp and relion extract particles support streaming mode.
I know this is a huge PR, and it is impossible to make a thorough review, but we can do an effort to take a look to find serious errors.

### CODE REVIEW

**Comment by josuegbl** [comment]
@pconesa, test is fixed. Please, re-run and check. Thanks

**Comment by azazellochg** [comment]
Hi all, I'll try to revieew it this week.

**Comment by pconesa** [comment]
Hi @azazellochg , is it ok if we release you from reviewing this?.

**Comment by delarosatrevin** [comment]
I agree that would be good to merge to release-1.1.facilities-devel and then @azazellochg can continue testing there and we can fix any bug that could emerge as usual.

**Comment by azazellochg** [comment]
yep, go ahead. Unfortunately, I don't have time until Saturday to look at this.

**Comment by pconesa** [comment]
@azazellochg no worries. We still can blame @josuegbl  and @delarosatrevin for any future bug introduced.

**Pull request merged**
