### PR TITLE
Facilities to headless

### PR DESCRIPTION
**Pull request by pconesa**
Updating headless with latest changes from facilities. 
File browser have shortcuts to common locations.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Hum... @pconesa is looks to me that there are many changed files? Isn't it? I wouldn't expect that this branch should be that different. In any case, I think we should updated first headless with facilities-devel and then the other way around.

**Comment by pconesa** [comment]
I'll review what I've done but I'm not surprised...we have done many thing the release-1.1.facilities...and...isn't this what I'm doing....facilities-devel -> headless (I used headless devel, because is what @kevinpetersavage asked and make sene...I think the headless is being stale for quite a long time.

**Comment by delarosatrevin** [comment]
Ok, I just was surprised by some many changes...I thought that headess was
not so out-of-date from facilities-devel

**Comment by pconesa** [comment]
I think current branch in use in DLS is headless-devel. @kevinpetersavage ?

**Comment by pconesa** [comment]
I'm closing this since we agreed to reverse the "flow".

**Pull request closed without merging**
