### PR TITLE
added project notebook in menu

### PR DESCRIPTION
**Pull request by rmarabini**
access: menu -> Project ->  notes
configuration: (in user scipion.conf)
[VARIABLES]
SCIPION_NOTES_PROGRAM = 
SCIPION_NOTES_ARGS = 
SCIPION_NOTES_FILE = notes.txt

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@rmarabini , I have made minor changes to keep scipion running even without those configuration variables. For me it is OK to merge. Test the latest changes and proceed with the merge.

**Comment by rmarabini** [comment]
Uhmm. The code seems to be OK but I do not know how to commit it:

X11 forwarding request failed on channel 0
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 326 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/devel.
remote: error: Required status check "continuous-integration/travis-ci" is
expected
To git@github.com:I2PC/scipion.git
 ! [remote rejected] devel -> devel (protected branch hook declined)
error: failed to push some refs to 'git@github.com:I2PC/scipion.git'


we may check this tomorrow.

   Roberto

**Comment by delarosatrevin** [comment]
You don't need to push from your local repository. You need to update with 'git pull'. 
The rm_menu branch is already merged into devel. So you can delete it now.

**Comment by rmarabini** [comment]
OK, branch deleted both locally and remotely

   Roberto

**Pull request merged**
