### PR TITLE
This merge contain all the changes introduced by @delarosatrevin in his branch sdevel.

### PR DESCRIPTION
**Pull request by josuegbl**

### CODE REVIEW

**Comment by pconesa** [comment]
I will feel more comfortable if we first accept the merge coming from facilities, that will simplify this one. Could you hold it until the I'm back next week?

**Comment by cossorzano** [comment]
There is something I don't fully understand from this branch. Could you explain how the GPUs are now handled at the level of forms?

**Comment by delarosatrevin** [comment]
Hi @cossorzano, I just wrote some notes about these changes related to GPU here:

https://github.com/I2PC/scipion/wiki/GPU-parameters-standardization-in-Scipion-protocols. 

Hope this helps.

**Comment by pconesa** [comment]
hi! @josuegbl or @delarosatrevin , I've pushed changes from facilities to devel and updated this branch, Now there are conflicts that are better for any of you to solve them.

**Comment by delarosatrevin** [comment]
@josuegbl I have made some changes to my sdevel branch (some bug fixes)...so I think you will need to update this one with devel (fixing conflicts) and then updating from mine. Or the other way around, not sure how to proceed. Or maybe easier to start again from devel and merge sdevel.

**Comment by josuegbl** [comment]
@pconesa, this is a weekend gift :smile: . Enjoy it hehehe

**Comment by josuegbl** [comment]
@pconesa, and this for when? I fixed all the conflicts 1 week ago, and this is still waiting...

**Comment by josuegbl** [comment]
I apologize if my words have sounded rude, it was not my intention. But a "thank you, I'll look at it" would have been welcome, after all the efforts so that the delarosatrevin's (not mine) code not diverge from it.

**Comment by delarosatrevin** [comment]
Thanks @josuegbl and @pconesa for taking a look into this. @josuegbl, as @pconesa said, there is no hurry for this PR. Indeed, we have been discussing to merge this changes into the release-1.2.1 branch for a upcoming release before the next major one. I'm open to discussion to what makes and make not sense to include there. So, maybe it will be better to review the PR merge to release-1.2.1 and then to devel.

**Comment by pconesa** [comment]
That is true, thank you @josuegbl  for this effort.
Guys, there are also some changes in thi PR that @josuegbl does not want to loos and probably will not go to release 1.2.1.....what about, accepting it, and also sending  @delarosatrevin changes to release 1.2.1 ?

**Comment by pconesa** [comment]
This can be cancelled,now  right?

**Comment by delarosatrevin** [comment]
I think so, since release-1.2.1 will be merged to master at some point. I would also be good to check if PR #1545 still makes sense.

**Comment by delarosatrevin** [comment]
@josuegbl has you committed more changes here? @pconesa asked if we could close this PR since these changes has been merged into release 1.2.1 branch...and you haven't replied.

**Comment by pconesa** [comment]
Hi! My idea is to leave this...I'm currently about to send release--1.2.1 to devel. Then this PR will have only those fixes.

**Comment by pconesa** [comment]
Hi! I'm closing this.....the differences panel does not make any sense. I don't know why, but the comparison is wrong.

**Pull request closed without merging**
