### PR TITLE
Tm micrographs preprocess streaming

### PR DESCRIPTION
**Pull request by majtner**
- preprocessing micrographs in streaming
- added new parameter to preprocessing: denoising (including all source codes)
- fixed small bug in testing preprocessing mics
- added new program/script for evaluation of coordinates = comparing two sets of coordinates (ground truth vs. new set), includes also tolerance parameter for small misplacements

### CODE REVIEW

**Comment by jordibc** [comment]
:)

**Comment by majtner** [comment]
I need this code to be reviewed soon, so I can use it in another branch for 2D clustering, where I am currently waiting for it.

**Comment by josuegbl** [comment]
@majtner, you can merge this branch in your  2D clustering branch without having to wait for the revision. A proper revision takes time and we're not much of it. 
In any case, you should add a test in streaming for the protocol. There are some tests implemented in streaming that you can use as example. Also, I see part of the modified code that which has nothing to do with preprocessing mics. I recommend you separate these in other PR.

**Comment by majtner** [comment]
@josuegbl If I will merge this branch to another one and start making changes, there might be conflicts, since I may modify something also in new denoising code. And I do not want to keep in mind, which part of the code belongs to which branch. 
I may join in all together but it will be very large and I will be requested to split it to more PR.

**Comment by cossorzano** [comment]
Fine with the C part

**Comment by josuegbl** [comment]
@majtner, the test for streaming is failing, at least for me, with following error:
00014:   xmipp_transform_filter -i Runs/000329_ProtCreateStreamData/extra/imageCTF_1.xmp --denoise --maxIter 50 -o Runs/000384_XmippProtPreprocessMicrographs/extra/imageCTF_1.mrc
00015:   XMIPP_ERROR 1: Errors on command line parameters
00016:   Unrecognized parameter: --denoise
00017:   Unrecognized parameter: --maxIter
00018:   
00019:   File: software/em/xmipp/libraries/data/argsparser.cpp line: 1036
00020:   For more info use --help
00021:   Traceback (most recent call last):
00022:     File "/home/josue/SOFTWARE/scipion/pyworkflow/protocol/executor.py", line 137, in run
00023:       self.step._run()  # not self.step.run() , to avoid race conditions
00024:     File "/home/josue/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 231, in _run
00025:       resultFiles = self._runFunc()
00026:     File "/home/josue/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 227, in _runFunc
00027:       return self._func(*self._args)
00028:     File "/home/josue/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 1116, in runJob
00029:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00030:     File "/home/josue/SOFTWARE/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00031:       env=env, cwd=cwd)
00032:     File "/home/josue/SOFTWARE/scipion/pyworkflow/utils/process.py", line 51, in runJob
00033:       return runCommand(command, env, cwd)
00034:     File "/home/josue/SOFTWARE/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00035:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00036:     File "/home/josue/SOFTWARE/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00037:       raise CalledProcessError(retcode, cmd)
00038:   CalledProcessError: Command 'xmipp_transform_filter -i Runs/000329_ProtCreateStreamData/extra/imageCTF_1.xmp --denoise --maxIter 50 -o Runs/000384_XmippProtPreprocessMicrographs/extra/imageCTF_1.mrc' returned non-zero exit status 1
00039:   Protocol failed: Command 'xmipp_transform_filter -i Runs/000329_ProtCreateStreamData/extra/imageCTF_1.xmp --denoise --maxIter 50 -o Runs/000384_XmippProtPreprocessMicrographs/extra/imageCTF_1.mrc' returned non-zero exit status 1
00040:   FAILED: runJob, step 1
00041:     2017-08-30 09:22:24.232203
00042:   ------------------- PROTOCOL FAILED (DONE 1/3)

**Comment by majtner** [comment]
@josuegbl I am sorry for this, problem was with our renaming of some parameters, should be fixed now

**Pull request merged**
