### PR TITLE
Allow to specify different hosts.conf through an environment variable

### PR DESCRIPTION
**Pull request by delarosatrevin**
In this PR two things are accomplished:
* Replace the use of the string 'hosts.conf'  by the variable SCIPION_CONFIG_HOSTS and,
* Allow that value to set externally via a environment variable. (This is useful to reuse the same installation for workstations and cluster which requires different hosts.conf files)

NOTE: I have created this branch after merging with facilities-fixes, so that PR should be merged first in order to see real changes introduced here.

### CODE REVIEW

**Comment by pconesa** [comment]
@delarosatrevin , isn't it the other way around. We must accept first facilities fixes?

**Comment by delarosatrevin** [comment]
Yes, that was what I intended to say, but you know...using a 'this' instead of a 'that' can mess it all over. I changed the original message. So, summarizing...facilities-fixes first and then this one.

**Comment by azazellochg** [comment]
I guess this "kind of" solves #1083 :)

**Comment by delarosatrevin** [comment]
@azazellochg Not sure if exactly the same...I think you want to have this in the same hosts.conf and in the same machine...and the difference should be by queue...

**Comment by pconesa** [comment]
@azazellochg , thanks.

**Pull request merged**
