### PR TITLE
Merge Scipion-Box into Devel branch

### PR DESCRIPTION
**Pull request by delarosatrevin**
@josuegbl , I have merged the devel into scipion-box and fixed the conflicts. I think now everything working still with minor things that we can address separately. 

Do some extra tests in this branch and proceed with the merge.

### CODE REVIEW

**Comment by josuegbl** [comment]
I found an error in motioncorr: If the input if a .mrc movie file the alignment is not properly stored in the sqlite. I updated the test to reflect the error.

**Comment by josuegbl** [comment]
Nothing to do: the correct values when the movie is stored is 0,0 in shifts values. The final results are ok. Test updated again....

**Comment by delarosatrevin** [comment]
@josuegbl , also double check the results (shifts included) of the unblur and summovie protocols that had some difference that I merged from devel.

**Comment by delarosatrevin** [comment]
Yes, important bug about frame numbering...thanks @azazellochg

**Comment by azazellochg** [comment]
One of motioncor tests fails in scipion-box branch. The shifts are wrong.
```
[   FAILED ] TestMotioncorrAlingMovies.test_qbeta

Traceback (most recent call last):
  File "/home/sharov/soft/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sharov/soft/scipion/pyworkflow/tests/em/protocols/test_protocols_motioncorr.py", line 104, in test_qbeta
    [-0.375,-0.4792,-0.2344,0.0,-0.1875, 0.2448]))
  File "/home/sharov/soft/scipion/pyworkflow/tests/em/protocols/test_protocols_motioncorr.py", line 94, in _checkAlignment
    type(shifts)))
  File "/home/sharov/soft/scipion/software/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/sharov/soft/scipion/software/lib/python2.7/unittest/case.py", line 753, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/home/sharov/soft/scipion/software/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/home/sharov/soft/scipion/software/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Alignment SHIFTS must be ([0.7135, 0.2344, 0.026, 0.0, 0.4375, 0.8073], [-0.375, -0.4792, -0.2344, 0.0, -0.1875, 0.2448]) (<type 'tuple'>) and it is ([2.5893, 0.7946, 0.2589, 0.0536, 0.0, 0.4643, 0.8705], [0.2545, -0.3304, -0.4375, -0.2277, 0.0, -0.0804, 0.1339]) (<type 'tuple'>)
```

**Pull request merged**
