### PR TITLE
PR for CTF selection protocol

### PR DESCRIPTION
**Pull request by josuegbl**

### CODE REVIEW

**Comment by pconesa** [comment]
@ajimoreno , this is a refactored code of the ctf filter. It would be nice if at some point @josuegbl explains you the reasons of this changes. 

Additionally, every new protocol "has to be added to the protocols.conf, in the right section if possible. I'll show you how to do this.

**Comment by pconesa** [comment]
@josuegbl can I delete this branch or will you use it for another PR?

**Comment by josuegbl** [comment]
NO, you cant. This branch is for merge all devel changes that should be
merged in release-1.1-facilities.

2017-06-26 13:58 GMT+02:00 Pablo Conesa <notifications@github.com>:

**Comment by delarosatrevin** [comment]
@josuegbl  I though that you have finished with all the features that were in that category. More branches, more confusion.

**Pull request merged**
