### PR TITLE
Picking protocol in Relion 2.0

### PR DESCRIPTION
**Pull request by delarosatrevin**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
There was a bug #935 that the picking wizard parameters were always set in the protocol form, independently if the user "closed" or "saved and exit". Now Java picker writes a property "applyChanges=true" if the user accepted changes. This property is read from the Python wizard code to decide if set the protocol form parameters.
I have tested the following wizards:
- Relion 2.0 autopicking
- Sparx gaussian
- Gautomatch
I think it should be working for the rest.

**Comment by josuegbl** [comment]
TEst fails due to diameter must be set manually.

Scipion  release-1.1-relion2 (2017-04-03) 7dd95f8

>>>>> python  /home/josue/SOFTWARE/scipion/pyworkflow/apps/pw_protocol_run.py "/home/josue/ScipionUserData/projects/TestWorkflowRelionPick" "Runs/000391_ProtRelion2Autopick/logs/run.db" "391"

>>> ERROR running protocol autopick gauss (optimize)
[   FAILED ] TestWorkflowRelionPick.test_ribo

Traceback (most recent call last):
  File "/home/josue/SOFTWARE/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/josue/SOFTWARE/scipion/pyworkflow/tests/em/workflows/test_workflow_relion.py", line 140, in test_ribo
    self.launchProtocol(protPick3)
  File "/home/josue/SOFTWARE/scipion/pyworkflow/tests/tests.py", line 106, in launchProtocol
    raise Exception("ERROR: Protocol not finished")
Exception: ERROR: Protocol not finished

**Comment by delarosatrevin** [comment]
Yes, I left this test failing because before I got informed (by someone with Relion picking experience) that the "mask diameter" (previously particle diameter) is needed even for the gaussian blobs case.

**Comment by josuegbl** [comment]
If you have more than 1 GPU (3 in my case) and launch the protocol specifying which GPU use (for instance 0 or 0:1) Relion has the following error:
00016:   STARTED: autopickStep, step 2
00017:     2017-04-05 12:06:06.676654
00018:   mpirun -np 3 -bynode  `which relion_autopick_mpi`  --pickname autopick --odir "" --particle_diameter -1 --angpix 7.080 --shrink 0.000 --max_stddev_noise 1.100 --gpu "0" --ref input_references.star --angpix_ref 7.080 --invert --ctf --ang 5 --lowpass 20  --i extra/151.star --threshold 0.250 --min_distance -1.000  --write_fom_maps
00019:   --------------------------------------------------------------------------
00020:   The following command line options and corresponding MCA parameter have
00021:   been deprecated and replaced as follows:
00022:   
00023:     Command line options:
00024:       Deprecated:  --bynode, -bynode
00025:       Replacement: --map-by node
00026:   
00027:     Equivalent MCA parameter:
00028:       Deprecated:  rmaps_base_bynode
00029:       Replacement: rmaps_base_mapping_policy=node
00030:   
00031:   The deprecated forms *will* disappear in a future version of Open MPI.
00032:   Please update to the new syntax.
00033:   --------------------------------------------------------------------------
00034:   WARNING : --write_fom_maps is very heavy on disc I/O and is not advised in parallel execution. If possible, using --shrink 0 and lowpass makes I/O less significant.
00035:    === RELION MPI setup ===
00036:    + Number of MPI processes             = 3
00037:    + Master  (0) runs on host            = finlay
00038:    + Slave     1 runs on host            = finlay
00039:    + Slave     2 runs on host            = finlay
00040:    =================
00041:    + Warning: input STAR file does not contain information about pixel size!
00042:    + Warning: use --angpix to provide the correct value. Now using 7.08 Angstroms
00043:    + Run autopicking on the following micrographs: 
00044:       * extra/151.mrc
00045:    + Automatically set the background diameter to 446.04 Angstrom
00046:    + You can override this by providing --particle_diameter (in Angstroms)
00047:    + WARNING: Requested rescale of micrographs is 690 pixels. The largest prime factor in FFTs is 173
00048:    + WARNING: Will change rescaling of micrographs to 684 pixels, because the prime factor then becomes 19
00049:    + WARNING: add --skip_optimise_scale to your autopick command to prevent rescaling 
00050:    + WARNING: The calculations will be done at a lower resolution than requested.
00051:    Initialising FFTs for the references and masks ... 
00056:      3/   3 sec ................................................~~(,_,">00057:   --------------------------------------------------------------------------
00058:   mpirun noticed that process rank 2 with PID 24794 on node finlay exited on signal 11 (Segmentation fault).

The protocol finish if uses all aviable GPUs

**Comment by delarosatrevin** [comment]
@josuegbl I haved added a default particleDiameter of 380 A, this should fix the failing test. I can not test it right now. 
I have made another small change, but very important and with a huge impact. Before, I was having one step for picking each micrograph...but this was very very slow, it was going to take about 7h for ~4000 micrographs dataset. Using a single step and relion_autopick with MPI was about 25 min.

**Comment by delarosatrevin** [comment]
Added first working version of 'relion-extract'. Test of the picking passing, except the known one that is failing that seems to be an error in relion.

**Pull request merged**
