### PR TITLE
add latest motioncor2

### LINKED ISSUE #797: Add motioncor2 new release..
Dear Colleagues,

The new version of MotionCor2 has been released on our website

http://msg.ucsf.edu/em/software/index.html

This version has implemented the following new functions in addition to bug fixing.

1. Correction of anisotropic magnification. This correction is integrated with the correction of local motion. There is no extra real-space interpolation as a result.
2. Archiving input movie stacks of 8 bits per pixel into MRC files with 4 bits per pixel.
3. Allow stacks to be aligned to user specified frames. 

This version is compiled with CUDA 8. For your convenience, the last version of MotionCor2 is still kept on our website.

Thank you all for your interests and feedbacks.

Best
Shawn

### PR DESCRIPTION
**Pull request by azazellochg**
closes #797 
To summarize:
1. Correction of anisotropic magnification - added input params, also Grigorieff's mag dist estimate protocol can be used as input
2. Set threads =1 since it doesn't use CPUs.
3. Fix errors when only DW sum was saved

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Thanks a lot @azazellochg ! I will try it as soon as I can.

**Comment by delarosatrevin** [comment]
@azazellochg, @pconesa, @josuegbl Since this change is somehow related with my streaming PR #920, what about the idea of merging the changes here into my branch and test all together there?

**Comment by josuegbl** [comment]
good for me

2017-03-22 14:10 GMT+01:00 Jose Miguel de la Rosa Trevin <
notifications@github.com>:

**Comment by azazellochg** [comment]
sure, I created a PR. @delarosatrevin you can merge and we could start testing

**Comment by delarosatrevin** [comment]
We will test this in #920

**Comment by delarosatrevin** [comment]
@azazellochg I already had an open PR.

**Pull request closed without merging**
