### PR TITLE
Release 1.1.facilities fixes

### PR DESCRIPTION
**Pull request by delarosatrevin**
@pconesa This PR is just a remainder that I need to merge these changes. I still want to do a modification to the new protocol and create the tests...I will let you know once finished for you to review it.

### CODE REVIEW

**Comment by josuegbl** [comment]
These changes are not fixes. You should create a specific branch to add the new protocol. 'm telling you from affection :)

**Comment by delarosatrevin** [comment]
Jejejeje...you are right @josuegbl. I used this branch by accident, I will not (or try) to use it for that in the future. For this time will be easier to just finish this PR first.

**Comment by pconesa** [comment]
@delarosatrevin , is it possible to merge this with your latest changes. HAvo some changes there that want to have in facilities. If not I'll cherry pick.

**Comment by delarosatrevin** [comment]
@pconesa My changes are not much...so maybe we can do what you said, merge the changes here as they are.

**Pull request merged**
