### PR TITLE
Fix picking #790

### LINKED ISSUE #790: automatic picked particles can be moved
When you try to move an automatic picked particle it is duplicated and the original is highlighted

### PR DESCRIPTION
**Pull request by pconesa**
For some reason this wasn't in release-1.1!

This fixes #790.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@pconesa this fix the issue of particles that could not be deleted? Because I have seen recently this case, that you have very green (bold) particles that can not be deleted during supervised mode of the picking.

**Comment by delarosatrevin** [comment]
I will check the changes here.

**Comment by pconesa** [comment]
Hi @delarosatrevin , yes, this was reported some time ago and I thought it was merged into release-1.1 but reviewing the branches discover this one and, my bad, it wasn't in the release-1.1 branch.

**Comment by delarosatrevin** [comment]
Tested and seems to be working. I haven't found anymore the un-mortal particles. 
As a plus, I have found a bug when creating a SetOfParticles after reviewing .

**Pull request merged**
