### PR TITLE
Rm resolution fit

### PR DESCRIPTION
**Pull request by rmarabini**
Hi @delarosatrevin ,

This is a new branch related with the introduction of resolution and fitQuality as parameters of the ctfModel.

./scipion test --grep ctf  --run

runs properly including program_stream_monitor

./scipion test tests.em.protocols.test_protocols_xmipp_mics.TestXmippExtractParticles

fails in a different protocol (after extracting the particles). I do not think the fail is related with the change

### CODE REVIEW

**Comment by delarosatrevin** [comment]
You are right @rmarabini , test are passing now, but still the extract particles is failing.
@josuegbl Can you take a look at this?

**Comment by josuegbl** [comment]
ok, I put it into my queue :)

**Comment by pconesa** [comment]
@rmarabini , previous changes (addition of resolution) is causing the 
`scipion test tests.em.data.test_convert_xmipp.TestSetConvert`
fail, I think test files do not have the new "_resolution" field.

**Comment by rmarabini** [comment]
OK, I will check.

**Pull request merged**
