### PR TITLE
updated protocols to run relion 2 beta

### PR DESCRIPTION
**Pull request by josuegbl**
NOw, classification (2d and 3d), auto-refine, pre and post-process can be executed with relion-2. Also, relion-postprocess can execute with any refinement protocol.

### CODE REVIEW

**Comment by pconesa** [comment]
closes #681 
closes #682

**Comment by pconesa** [comment]
To test with R2.0:
- [ ]  2d and 3d classification
- [ ] autorefine
- [ ] preprocess
- [ ] postprocess
- [ ] Test projection matching (projmatch)
- [ ]  refineeasy (eman)
- [ ]  frealign

**Comment by josuegbl** [comment]
closes #722

**Comment by pconesa** [comment]
Good job @josuegbl, merging now!

**Pull request merged**
